languages:
  JavaScript: true
engines:
  eslint:
    enabled: true
exclude_paths:
- styles/*
- public/*
- tests/*
- coverage/*
- lib/*
- webpack/*
- config/*
- src/server/db/migrations/*
- src/server/db/models/*
- src/shared/utils/semantic-custom.js
- src/vendor/*
